# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Enable entities light source.
	entities = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

			[light_sources.settings.entities.minecraft]
				chicken = true
				arrow = true
				cow = true
				pig = true
				skeleton = true
				iron_golem = true
				bat = true
				husk = true
				armadillo = true
				camel = true
				rabbit = true
				cat = true
				zombie = true
				sheep = true
				experience_orb = true
				player = true
				item = true
				turtle = true
				villager = true
				salmon = true
				goat = true
				horse = true
				glow_squid = true
				glow_item_frame = false
				spider = true
				creeper = true
				enderman = true
